# Generated by Django 5.2.5 on 2025-09-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_role_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
