# Generated by Django 5.2.5 on 2025-09-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='Permissions',
        ),
    ]
