# Generated by Django 5.2.5 on 2025-09-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_permission_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.role'),
        ),
    ]
