# Generated by Django 5.2.5 on 2025-09-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='company.permissions'),
        ),
    ]
