# Generated by Django 5.2.5 on 2025-09-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='codename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
